# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='catagory',
            new_name='category',
        ),
    ]
