# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20180417_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[restaurants.validators.validate_caterogy]),
        ),
    ]
