# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default=1, max_length=255, validators=[restaurants.validators.validate_caterogy]),
            preserve_default=False,
        ),
    ]
